services:
  redis:
    ports:
      - 6380:6379
    container_name: "redis"
    image: redis:alpine

  api:
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    container_name: "api"
    tty: true
    build:
      context: ./BE
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:1234@db/herson_api?schema=public

  db:
    ports:
      - 5433:5432
    container_name: "db"
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: herson_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: postgres
