ARG NODE_VERSION=20.17.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate

EXPOSE 3000

CMD [  "npm", "run", "start:migrate:prod" ]
