export enum ApiPath {
  user = "/user",
  userSearch = "/user/search",
  news = "/news",
  categories = "/categories",
  userProfile = "/user/profile",
  comments = "/comments",
  votings = "/votings",
  votingsAnswers = "/votings/answers",
  surveys = "/surveys",
  surveysAnswers = "/surveys/answers",
  forums = "/forums",
  fundraisings = "/fundraisings",
  fundraisingsCategories = "/fundraising-categories",
  paymentCheckout = "/payment/checkout",
  chat = "/chat",
  chatMsg = "/chat-msg",
}
